use_frameworks!
source "https://github.com/benmarten/CocoaPods-Test-Repository.git"

target 'lib2_Example' do
  pod 'lib2', :path => '../'
  #pod 'lib1', :path => '../../lib1/'
  target 'lib2_Tests' do
    inherit! :search_paths


  end
end
